language: go

go:
  - 1.8.x
  - master

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2

notifications:
  email:
    recipients:
      - mzhjensen@gmail.com
    on_success: never
    on_failure: always